title: MAASL Documentation
description: The documentation for MAASL, The Marnix Adaptive All-around Scripting Language.
show_downloads: false
google_analytics: UA-162896410-1
theme: jekyll-theme-midnight
